# Generated by Django 4.2.2 on 2023-06-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0006_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='twitter_link',
        ),
    ]
