# Generated by Django 4.2.2 on 2023-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0007_rename_homepage_link_profile_twitter_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
